// GENERATED by C:\yutrix\gen-demo-timeline.py - do not edit by hand.
// Cue times are derived from the real clip durations, so they stay in step with
// the audio. Re-run the generator if any clip is re-rendered.

export type DemoSpeaker = "agent" | "customer";

export interface DemoCue {
  /** Seconds into the scenario audio at which this line is pushed. */
  at: number;
  speaker: DemoSpeaker;
  text: string;
}

export interface DemoScenario {
  audioSrc: string;
  durationSec: number;
  cues: DemoCue[];
}

export const DEMO_SCENARIOS: Record<string, DemoScenario> = {
  ready_to_pay: {
    audioSrc: "/audio/scenario-ready-to-pay-ar-KW.mp3",
    durationSec: 103.5,
    cues: [
      { at: 5.07, speaker: "customer", text: "Hello, peace be upon you." },
      { at: 10.07, speaker: "agent", text: "Good morning. This is Ahmed from the collections team. Am I speaking with Fahad Al-Otaibi?" },
      { at: 16.04, speaker: "customer", text: "Yes, this is Fahad Al-Otaibi. Go ahead." },
      { at: 21.04, speaker: "agent", text: "Thank you. I'm calling about the overdue installment on your personal loan." },
      { at: 26.58, speaker: "customer", text: "Yes, I know. I have a late installment." },
      { at: 31.58, speaker: "agent", text: "Your account is showing an overdue balance from last month's installment." },
      { at: 35.36, speaker: "customer", text: "How much exactly is due?" },
      { at: 40.36, speaker: "agent", text: "It's one hundred and fifty dinars. Are you able to settle that?" },
      { at: 46.33, speaker: "customer", text: "Fine, I can pay. No problem." },
      { at: 51.33, speaker: "agent", text: "That's good to hear. What exact date will you make the payment?" },
      { at: 58.57, speaker: "customer", text: "I'll pay on the 25th of this month, after my salary arrives." },
      { at: 63.57, speaker: "agent", text: "Noted, the twenty-fifth. And how much will you be paying that day?" },
      { at: 69.58, speaker: "customer", text: "I'll pay the full amount, one hundred and fifty dinars." },
      { at: 74.58, speaker: "agent", text: "Perfect. And how will you pay - branch, app, or transfer?" },
      { at: 79.59, speaker: "customer", text: "I'll transfer it through the app, online." },
      { at: 84.59, speaker: "agent", text: "Let me confirm: one hundred fifty dinars, on the twenty-fifth, by online transfer?" },
      { at: 93.68, speaker: "customer", text: "Yes, I confirm: the 25th, one hundred and fifty dinars, online transfer." },
      { at: 98.68, speaker: "agent", text: "Thank you, Mr. Fahad. You'll receive a confirmation message. Have a good day." },
      { at: 103.5, speaker: "customer", text: "Thank you. Goodbye." },
    ],
  },
  not_ready_to_pay: {
    audioSrc: "/audio/scenario-not-ready-to-pay-ar-KW.mp3",
    durationSec: 111.54,
    cues: [
      { at: 4.54, speaker: "customer", text: "Hello, who am I speaking with?" },
      { at: 9.54, speaker: "agent", text: "Good morning. This is Ahmed from the collections team. Is this Yousef Al-Rashidi?" },
      { at: 14.43, speaker: "customer", text: "Yes, this is Yousef. Go ahead." },
      { at: 19.43, speaker: "agent", text: "Thank you. I'm calling about the overdue installment on your personal loan." },
      { at: 25.62, speaker: "customer", text: "I know the installment is late, but my circumstances are difficult right now." },
      { at: 30.62, speaker: "agent", text: "I understand. Can you tell me what's changed in your situation?" },
      { at: 36.9, speaker: "customer", text: "I lost my job two months ago and haven't found work yet." },
      { at: 41.9, speaker: "agent", text: "I'm sorry to hear that. Is there any way to clear the full amount?" },
      { at: 47.26, speaker: "customer", text: "Honestly, I can't pay the full amount this month." },
      { at: 52.26, speaker: "agent", text: "I understand. What other commitments are you managing at the moment?" },
      { at: 58.98, speaker: "customer", text: "I have medical expenses for my mother, and those eat most of my income." },
      { at: 63.98, speaker: "agent", text: "That's a real burden. Could you manage a smaller partial payment instead?" },
      { at: 70.09, speaker: "customer", text: "I could pay a small amount, say thirty dinars." },
      { at: 75.09, speaker: "agent", text: "Thirty dinars is workable. When would you be able to pay that?" },
      { at: 81.51, speaker: "customer", text: "Can you give me a grace period? I need at least a month." },
      { at: 86.51, speaker: "agent", text: "I can request a hold. We may also be able to restructure the loan." },
      { at: 92.29, speaker: "customer", text: "If rescheduling is possible, I'd be grateful." },
      { at: 97.29, speaker: "agent", text: "I'll raise it today. Can you commit to thirty dinars this month?" },
      { at: 102.99, speaker: "customer", text: "Alright, I can commit to thirty dinars on the 10th." },
      { at: 107.99, speaker: "agent", text: "Thank you, Mr. Yousef. I've noted thirty dinars on the tenth." },
      { at: 111.54, speaker: "customer", text: "Thank you for your understanding." },
    ],
  },
};
