// GENERATED by C:\yutrix\gen-demo-timeline.py - do not edit by hand.
// Cue times are derived from the real clip durations, so they stay in step with
// the audio. Re-run the generator if any clip is re-rendered.

export type DemoSpeaker = "agent" | "customer";

export interface DemoCue {
  /** Seconds into the scenario audio at which this line is pushed. */
  at: number;
  speaker: DemoSpeaker;
  /** English. This is the ONLY wording sent to the copilot, so insights stay English. */
  text: string;
  /** Arabic (Kuwait), shown alongside the English in the live transcript. */
  textAr: string;
}

export interface DemoScenario {
  audioSrc: string;
  durationSec: number;
  cues: DemoCue[];
}

export const DEMO_SCENARIOS: Record<string, DemoScenario> = {
  ready_to_pay: {
    audioSrc: "/audio/scenario-ready-to-pay-ar-KW.mp3",
    durationSec: 103.5,
    cues: [
      {
        at: 5.07,
        speaker: "customer",
        text: "Hello, peace be upon you.",
        textAr: "آلو، السلام عليكم.",
      },
      {
        at: 10.07,
        speaker: "agent",
        text: "Good morning. This is Ahmed from the collections team. Am I speaking with Fahad Al-Otaibi?",
        textAr: "صباح الخير. معك أحمد من قسم التحصيل. هل أتحدث مع فهد العتيبي؟",
      },
      {
        at: 16.04,
        speaker: "customer",
        text: "Yes, this is Fahad Al-Otaibi. Go ahead.",
        textAr: "نعم، أنا فهد العتيبي. تفضل.",
      },
      {
        at: 21.04,
        speaker: "agent",
        text: "Thank you. I'm calling about the overdue installment on your personal loan.",
        textAr: "شكراً لك. أتصل بخصوص القسط المتأخر على قرضك الشخصي.",
      },
      {
        at: 26.58,
        speaker: "customer",
        text: "Yes, I know. I have a late installment.",
        textAr: "إي، أعرف. عندي قسط متأخر.",
      },
      {
        at: 31.58,
        speaker: "agent",
        text: "Your account is showing an overdue balance from last month's installment.",
        textAr: "يظهر في حسابك مبلغ متأخر من قسط الشهر الماضي.",
      },
      {
        at: 35.36,
        speaker: "customer",
        text: "How much exactly is due?",
        textAr: "كم المبلغ المطلوب بالضبط؟",
      },
      {
        at: 40.36,
        speaker: "agent",
        text: "It's one hundred and fifty dinars. Are you able to settle that?",
        textAr: "المبلغ مية وخمسين دينار. هل تقدر تسدده؟",
      },
      {
        at: 46.33,
        speaker: "customer",
        text: "Fine, I can pay. No problem.",
        textAr: "تمام، أقدر أسدد. ما في مشكلة.",
      },
      {
        at: 51.33,
        speaker: "agent",
        text: "That's good to hear. What exact date will you make the payment?",
        textAr: "هذا خبر طيب. في أي تاريخ بالضبط راح تسدد؟",
      },
      {
        at: 58.57,
        speaker: "customer",
        text: "I'll pay on the 25th of this month, after my salary arrives.",
        textAr: "راح أسدد يوم خمسة وعشرين من هذا الشهر، بعد ما ينزل الراتب.",
      },
      {
        at: 63.57,
        speaker: "agent",
        text: "Noted, the twenty-fifth. And how much will you be paying that day?",
        textAr: "تم التسجيل، يوم خمسة وعشرين. وكم المبلغ الذي ستدفعه ذلك اليوم؟",
      },
      {
        at: 69.58,
        speaker: "customer",
        text: "I'll pay the full amount, one hundred and fifty dinars.",
        textAr: "راح أدفع المبلغ كامل، مية وخمسين دينار.",
      },
      {
        at: 74.58,
        speaker: "agent",
        text: "Perfect. And how will you pay - branch, app, or transfer?",
        textAr: "ممتاز. وكيف ستدفع — من الفرع، أو التطبيق، أو تحويل؟",
      },
      {
        at: 79.59,
        speaker: "customer",
        text: "I'll transfer it through the app, online.",
        textAr: "بحوّلها عن طريق التطبيق، أونلاين.",
      },
      {
        at: 84.59,
        speaker: "agent",
        text: "Let me confirm: one hundred fifty dinars, on the twenty-fifth, by online transfer?",
        textAr: "دعني أؤكد: مية وخمسين دينار، يوم خمسة وعشرين، عن طريق تحويل أونلاين؟",
      },
      {
        at: 93.68,
        speaker: "customer",
        text: "Yes, I confirm: the 25th, one hundred and fifty dinars, online transfer.",
        textAr: "إي، أأكد لك. يوم خمسة وعشرين، مية وخمسين دينار، تحويل أونلاين.",
      },
      {
        at: 98.68,
        speaker: "agent",
        text: "Thank you, Mr. Fahad. You'll receive a confirmation message. Have a good day.",
        textAr: "شكراً لك أستاذ فهد. ستصلك رسالة تأكيد. أتمنى لك يوماً سعيداً.",
      },
      {
        at: 103.5,
        speaker: "customer",
        text: "Thank you. Goodbye.",
        textAr: "شكراً لك. مع السلامة.",
      },
    ],
  },
  not_ready_to_pay: {
    audioSrc: "/audio/scenario-not-ready-to-pay-ar-KW.mp3",
    durationSec: 111.54,
    cues: [
      {
        at: 4.54,
        speaker: "customer",
        text: "Hello, who am I speaking with?",
        textAr: "آلو، مين معاي؟",
      },
      {
        at: 9.54,
        speaker: "agent",
        text: "Good morning. This is Ahmed from the collections team. Is this Yousef Al-Rashidi?",
        textAr: "صباح الخير. معك أحمد من قسم التحصيل. هل أتحدث مع يوسف الرشيدي؟",
      },
      {
        at: 14.43,
        speaker: "customer",
        text: "Yes, this is Yousef. Go ahead.",
        textAr: "إي، أنا يوسف. تفضل.",
      },
      {
        at: 19.43,
        speaker: "agent",
        text: "Thank you. I'm calling about the overdue installment on your personal loan.",
        textAr: "شكراً لك. أتصل بخصوص القسط المتأخر على قرضك الشخصي.",
      },
      {
        at: 25.62,
        speaker: "customer",
        text: "I know the installment is late, but my circumstances are difficult right now.",
        textAr: "أعرف إن القسط متأخر، بس ظروفي صعبة الحين.",
      },
      {
        at: 30.62,
        speaker: "agent",
        text: "I understand. Can you tell me what's changed in your situation?",
        textAr: "أتفهم ذلك. ممكن تخبرني ما الذي تغير في وضعك؟",
      },
      {
        at: 36.9,
        speaker: "customer",
        text: "I lost my job two months ago and haven't found work yet.",
        textAr: "فقدت وظيفتي قبل شهرين، ولين الحين ما لقيت شغل.",
      },
      {
        at: 41.9,
        speaker: "agent",
        text: "I'm sorry to hear that. Is there any way to clear the full amount?",
        textAr: "يؤسفني سماع ذلك. هل هناك أي طريقة لتسديد المبلغ كاملاً؟",
      },
      {
        at: 47.26,
        speaker: "customer",
        text: "Honestly, I can't pay the full amount this month.",
        textAr: "والله ما أقدر أدفع المبلغ كامل هذا الشهر.",
      },
      {
        at: 52.26,
        speaker: "agent",
        text: "I understand. What other commitments are you managing at the moment?",
        textAr: "أتفهم. ما هي الالتزامات الأخرى التي تتحملها حالياً؟",
      },
      {
        at: 58.98,
        speaker: "customer",
        text: "I have medical expenses for my mother, and those eat most of my income.",
        textAr: "عندي مصاريف علاج لوالدتي، وهذي اللي تاكل أغلب الراتب.",
      },
      {
        at: 63.98,
        speaker: "agent",
        text: "That's a real burden. Could you manage a smaller partial payment instead?",
        textAr: "هذا عبء حقيقي. هل يمكنك دفع مبلغ جزئي أصغر بدلاً من ذلك؟",
      },
      {
        at: 70.09,
        speaker: "customer",
        text: "I could pay a small amount, say thirty dinars.",
        textAr: "ممكن أدفع مبلغ بسيط، مثلاً ثلاثين دينار.",
      },
      {
        at: 75.09,
        speaker: "agent",
        text: "Thirty dinars is workable. When would you be able to pay that?",
        textAr: "ثلاثين دينار مبلغ مقبول. متى يمكنك دفعه؟",
      },
      {
        at: 81.51,
        speaker: "customer",
        text: "Can you give me a grace period? I need at least a month.",
        textAr: "تقدرون تعطوني مهلة؟ أحتاج شهر على الأقل.",
      },
      {
        at: 86.51,
        speaker: "agent",
        text: "I can request a hold. We may also be able to restructure the loan.",
        textAr: "أستطيع طلب تجميد مؤقت. وقد نتمكن أيضاً من إعادة هيكلة القرض.",
      },
      {
        at: 92.29,
        speaker: "customer",
        text: "If rescheduling is possible, I'd be grateful.",
        textAr: "إذا في إمكانية إعادة جدولة، أكون ممنون.",
      },
      {
        at: 97.29,
        speaker: "agent",
        text: "I'll raise it today. Can you commit to thirty dinars this month?",
        textAr: "سأرفع الطلب اليوم. هل تلتزم بثلاثين دينار هذا الشهر؟",
      },
      {
        at: 102.99,
        speaker: "customer",
        text: "Alright, I can commit to thirty dinars on the 10th.",
        textAr: "زين، أقدر ألتزم بثلاثين دينار يوم عشرة.",
      },
      {
        at: 107.99,
        speaker: "agent",
        text: "Thank you, Mr. Yousef. I've noted thirty dinars on the tenth.",
        textAr: "شكراً لك أستاذ يوسف. سجلت ثلاثين دينار يوم عشرة.",
      },
      {
        at: 111.54,
        speaker: "customer",
        text: "Thank you for your understanding.",
        textAr: "شكراً على تفهمك.",
      },
    ],
  },
};
