spring:
  ai:
    bedrock:
      aws:
        region: ${AWS_REGION}
        access-key: ${AWS_ACCESS_KEY_ID}
        secret-key: ${AWS_SECRET_ACCESS_KEY}
    openai:
      api-key: ${OPENAI_API_KEY}
    vertex:
      ai:
        gemini:
          project-id: ${GCP_PROJECT_ID}
          location: ${GCP_LOCATION}

server:
  port: 8080
  servlet:
    context-path: /collassistantapi

exotel:
  subdomain: api.in.exotel.com
  account-sid: ${EXOTEL_ACCOUNT_SID:fintaar2m}
  auth-key: ${EXOTEL_AUTH_KEY}
  auth-token: ${EXOTEL_AUTH_TOKEN}
  caller-id: ${EXOTEL_CALLER_ID:02247790125}

livekit:
  url: ${LIVEKIT_URL:wss://test125-h4h82mth.livekit.cloud}
  api-key: ${LIVEKIT_API_KEY}
  api-secret: ${LIVEKIT_API_SECRET}

app:
  cors:
    allowed-origins: https://aiassistant.yutrix.io

next-action:
  api-url: https://cep.yutrix.io/nextactionapi/V1/analyse/ai-assistant-analyze

logging:
  level:
    labs.yutrix.uw: DEBUG
    org.springframework.web.socket: DEBUG
