package labs.yutrix.uw.insight;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Disposition data generated by AI for call outcome recommendation.
 * Part of the copilot response schema.
 * Validation relaxed to accept any LLM output format.
 */
public record DispositionData(
                String result,
                Double confidence,
                String date,
                Double amount,
                String reason,
                String notes,
                @JsonProperty("next_action") String nextAction,
                String reasoning) {
}
