"""Collections copilot — thin adapter wrapping the existing InsightEngine.

All internal logic, prompts, schemas, and behavior remain identical.
This is purely a structural refactor to fit the BaseCopilot interface.
"""

import logging
from copilot.base import BaseCopilot
from insight_engine import InsightEngine

logger = logging.getLogger(__name__)


class CollectionsCopilot(BaseCopilot):
    """Delegates all calls to the existing InsightEngine without modification."""

    def __init__(self, call_sid: str, http_session, mobile_number: str | None = None):
        self._engine = InsightEngine(call_sid, http_session, mobile_number)

    async def initialize(self):
        await self._engine.initialize()

    async def process_utterance(self, speaker: str, text: str, timestamp: str):
        await self._engine.process_utterance(speaker, text, timestamp)

    async def on_call_end(self):
        # Collections disposition is generated by Java's DispositionService, not Python.
        logger.info("CollectionsCopilot.on_call_end — no-op (Java handles disposition)")
